server:
  port: 9091
spring:
  boot:
    admin:
      client:
        url: http://localhost:9090
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"