# 应用服务 WEB 访问端口
server:
  port: 8080





#spring:
#  datasource:
#    driver-class-name:
#    url:
#    username:
#    password: 123456
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/fmmall?characterEncoding=utf-8
      username: root
      password: 123456



